# Generated by Django 3.2.7 on 2021-10-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_to_db', '0002_alter_esportteammodel_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportViaDjangoImportExportDependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='EsportTeamModel',
            new_name='ImportViaShell',
        ),
    ]
